# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Python_Labview(object):
    def setupUi(self, Python_Labview):
        Python_Labview.setObjectName("Python_Labview")
        Python_Labview.resize(231, 108)
        self.start_button = QtWidgets.QPushButton(Python_Labview)
        self.start_button.setGeometry(QtCore.QRect(30, 20, 75, 23))
        self.start_button.setObjectName("start_button")
        self.stop_button = QtWidgets.QPushButton(Python_Labview)
        self.stop_button.setGeometry(QtCore.QRect(120, 20, 75, 23))
        self.stop_button.setObjectName("stop_button")
        self.data_line = QtWidgets.QLineEdit(Python_Labview)
        self.data_line.setGeometry(QtCore.QRect(80, 60, 113, 20))
        self.data_line.setObjectName("data_line")
        self.data_label = QtWidgets.QLabel(Python_Labview)
        self.data_label.setGeometry(QtCore.QRect(30, 60, 51, 21))
        self.data_label.setObjectName("data_label")

        self.retranslateUi(Python_Labview)
        QtCore.QMetaObject.connectSlotsByName(Python_Labview)

    def retranslateUi(self, Python_Labview):
        _translate = QtCore.QCoreApplication.translate
        Python_Labview.setWindowTitle(_translate("Python_Labview", "Python_Labview"))
        self.start_button.setText(_translate("Python_Labview", "Start"))
        self.stop_button.setText(_translate("Python_Labview", "Stop"))
        self.data_label.setText(_translate("Python_Labview", "Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Python_Labview = QtWidgets.QWidget()
    ui = Ui_Python_Labview()
    ui.setupUi(Python_Labview)
    Python_Labview.show()
    sys.exit(app.exec_())
