# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Python_Labview(object):
    def setupUi(self, Python_Labview):
        Python_Labview.setObjectName("Python_Labview")
        Python_Labview.resize(209, 253)
        self.send_button = QtWidgets.QPushButton(Python_Labview)
        self.send_button.setEnabled(False)
        self.send_button.setGeometry(QtCore.QRect(10, 90, 75, 23))
        self.send_button.setObjectName("send_button")
        self.start_button = QtWidgets.QPushButton(Python_Labview)
        self.start_button.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.start_button.setObjectName("start_button")
        self.stop_button = QtWidgets.QPushButton(Python_Labview)
        self.stop_button.setEnabled(False)
        self.stop_button.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.stop_button.setObjectName("stop_button")
        self.frame = QtWidgets.QFrame(Python_Labview)
        self.frame.setGeometry(QtCore.QRect(100, 10, 91, 61))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.data_line = QtWidgets.QLineEdit(self.frame)
        self.data_line.setGeometry(QtCore.QRect(10, 30, 71, 20))
        self.data_line.setObjectName("data_line")
        self.data_label = QtWidgets.QLabel(self.frame)
        self.data_label.setGeometry(QtCore.QRect(10, 0, 41, 21))
        self.data_label.setObjectName("data_label")
        self.frame_2 = QtWidgets.QFrame(Python_Labview)
        self.frame_2.setGeometry(QtCore.QRect(100, 90, 91, 151))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.indicator_line = QtWidgets.QLineEdit(self.frame_2)
        self.indicator_line.setGeometry(QtCore.QRect(10, 20, 71, 20))
        self.indicator_line.setObjectName("indicator_line")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 0, 55, 16))
        self.label.setObjectName("label")
        self.command_line = QtWidgets.QLineEdit(self.frame_2)
        self.command_line.setGeometry(QtCore.QRect(10, 70, 71, 20))
        self.command_line.setObjectName("command_line")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 61, 16))
        self.label_3.setObjectName("label_3")
        self.payload_double = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.payload_double.setGeometry(QtCore.QRect(10, 120, 71, 22))
        self.payload_double.setObjectName("payload_double")

        self.retranslateUi(Python_Labview)
        QtCore.QMetaObject.connectSlotsByName(Python_Labview)

    def retranslateUi(self, Python_Labview):
        _translate = QtCore.QCoreApplication.translate
        Python_Labview.setWindowTitle(_translate("Python_Labview", "Python_Labview"))
        self.send_button.setText(_translate("Python_Labview", "Send"))
        self.start_button.setText(_translate("Python_Labview", "Start"))
        self.stop_button.setText(_translate("Python_Labview", "Stop"))
        self.data_label.setText(_translate("Python_Labview", "Data"))
        self.label.setText(_translate("Python_Labview", "Indicator"))
        self.label_2.setText(_translate("Python_Labview", "Command"))
        self.label_3.setText(_translate("Python_Labview", "Payload"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Python_Labview = QtWidgets.QWidget()
    ui = Ui_Python_Labview()
    ui.setupUi(Python_Labview)
    Python_Labview.show()
    sys.exit(app.exec_())
